#!/bin/bash

#get script dir - https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

 $SCRIPT_DIR/python $SCRIPT_DIR/../../manage.py $1 $2 $3 $4 $5 $6 $7 $8 $9