version: 2.1

executors:
  ubunto-16_04:
    docker:
      - image: innovizswt/swt-base:1.0.1-ubuntu-16.04
  ubunto-18_04:
    docker:
      - image: innovizswt/swt-base:1.0.1-ubuntu-18.04
  ubunto-20_04:
    docker:
      - image: innovizswt/swt-base:1.0.1-ubuntu-20.04

jobs:
  test:
    parameters:
      os:
        type: executor
      python-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          command: |
            pyenv install << parameters.python-version >>
            pyenv global << parameters.python-version >> 3.9.1
            python --version
            python envsetup.py
            source env/bin/activate
            python manage.py -t
          name: Test
          
workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              os: [ubunto-16_04, ubunto-18_04, ubunto-20_04]
              python-version: ["3.6.5", "3.7.0", "3.8.0", "3.9.0"]
